name: Cereus

on: push

jobs:
  build:
    name: Cereus;
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Build Kernel
      run: |
        chmod a+x ./cereus.sh
        ./cereus.sh
      shell: bash
      env:
        ci_secret: ${{ secrets.CI_SECRET }} 
        GITOKEN: ${{ secrets.GITOKEN }}
